---

- name: Add nextcloud repository key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 1FCD77DD0DBEF5699AD2610160EE47FBAD3DD469

- name: Configure nextcloud repository
  apt_repository:
    repo: deb http://ppa.launchpad.net/nextcloud-devs/client/ubuntu bionic main

- name: Install nextcloud packages
  apt:
    update_cache: yes
    state: present
    pkg:
    - nextcloud-client
