---

- name: Install auditd package
  apt:
    name: auditd
    state: present

- name: Configure auditd
  copy:
    src: auditd-rules.d
    dest: /etc/audit/rules.d
    owner: root
    group: root
    mode: '0640'
    directory_mode: '0750'
  register: configure_auditd

- name: Restart auditd service
  service:
    name: auditd
    state: restarted
  when: configure_auditd.changed

- name: Enable auditd service
  service:
    name: auditd
    enabled: true

- name: Configure auditd logrotation
  copy:
    dest: /etc/logrotate.d/auditd
    src: auditd-logrotation
    owner: root
    group: root
    mode: '0644'